# Server Configuration
server.port=8080
spring.application.name=polling-app

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pollingdb
spring.datasource.username=yeswanthvajja
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.polling=DEBUG
